<?php
    $this->inlineScript()->appendFile( $this->basePath('/plugins/ldscarousel/js/jquery.ldscarousel.js') )
                         ->appendFile( $this->basePath('/js/products.js') );
    
    $this->headScript()->prependFile( $this->basePath('/plugins/fancybox/js/jquery.fancybox-thumbs.js') )
                       ->prependFile( $this->basePath('/plugins/fancybox/js/jquery.fancybox.js') );
    
    $this->headLink()->appendStylesheet( $this->basePath('/plugins/fancybox/css/jquery.fancybox.css') )
                     ->appendStylesheet( $this->basePath('/plugins/fancybox/css/jquery.fancybox-buttons.css') )
                     ->appendStylesheet( $this->basePath('/plugins/fancybox/css/jquery.fancybox-thumbs.css') )
                     ->appendStylesheet( $this->basePath('/plugins/ldscarousel/css/jquery.ldscarousel.css') )
                     ->appendStylesheet( $this->basePath('/css/products.css') )
                     ;
?>
                    
                    <?php  foreach($this->resultset as $key => $value) { ?>
                    <h1><?php echo( $value['product_name'] ) ?></h1>
                    
                    <div class="splash container single backshadow product draggable">

                        <div class="header drag_handle">
                            
                            <div class="icon">
                                <img src="<?php echo $this->basePath('/img/manufacturers/logos/expolinc-logo.svg'); ?>" class="manufacturer icon">
                            </div>
                            
                            <div class="actions">
                                <ul>
                                    <li data-sidebar-interact='true' data-for='varukorg'>
                                        <a href="#buy" <?php if( array_key_exists('variants', $value ) ) { ?>class='has-children'<?php } ?>> <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> Köp </a>
                                        <div class="data hidden" data-id="<?php echo( $value['product_id'] ); ?>" data-name="<?php echo( $value['product_name'] ); ?>" data-icon="rollup_classic_large.png" data-manufacturer="<?php echo( $value['manufacturer'] ); ?>" data-price="<?php echo( $value['fran_price'] ); ?>" data-vat="25"></div>
                                        
                                        <?php if( array_key_exists('variants', $value ) ) { ?>
                                        <ul class="has-children">
                                            
                                            <?php foreach( $value['variants'] as $v_key => $v_value ) { ?>
                                            <li>
                                                <a href="#buy">
                                                    <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> <?php echo( $v_value['product_variant'] ); ?>
                                                    <div class="clear"></div>
                                                </a>
                                                <div class="data hidden" data-id="<?php echo( $v_value['product_id'] ); ?>" data-name="<?php echo( $v_value['product_name'] ); ?>" data-icon="rollup_classic_large.png" data-manufacturer="<?php echo( $v_value['manufacturer'] ); ?>" data-price="<?php echo( $v_value['fran_price'] ); ?>" data-vat="25"></div>
                                            </li>
                                            <?php } ?>
                                            
                                        </ul>
                                        <?php } ?>
                                        
                                    </li>
                                    <li> <a href="#add"> <img src="<?php echo $this->basePath('img/ui/icons/add_to_list.svg'); ?>"> Lägg till i lista </a> </li>
                                    <li>
                                        <input type="checkbox" id="compare-1" name="compare-1" class="compare">
                                        <label for="compare-1" class="compare">Jämför</label>
                                    </li>
                                </ul>
                            </div>

                            <h3><a href="<?php echo $this->basePath('/produkter/'.$value['product_seo']) . PHP_EOL; ?>" title="<?php echo( $value['product_name'] ); ?>"><?php echo( $value['product_name'] ); ?></a></h3>
                            
                            <ul class='information'>
                                <li>
                                    <a href="<?php echo $this->basePath('/tillverkare/'.$value['manufacturer_seo']) . PHP_EOL; ?>" title="<?php echo( $value['manufacturer'] ); ?>"><?php echo( $value['manufacturer'] ); ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('/kategori/roll_ups') . PHP_EOL; ?>" title="Roll-Ups">Roll-Ups</a>
                                </li>
                            </ul>
                            
                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount"><?php echo( $value['fran_price'] ); ?>:-</p>
                            </div>

                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image carousel_wrapper">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            
                            <div class="prev">
                                <a href="#prev"> <img src="/plugins/ldscarousel/img/prev-arrow.png" /> </a>
                            </div>
                            
                            <div class="carousel">
                                
                                <ul>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" data-fancybox-group="roll_up_classic_carousel" title="Roll-Up Classic" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="focus">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_mekanik.png'); ?>" data-fancybox-group="roll_up_classic_carousel" title="Roll-Up Classic, Mekanik" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_mekanik.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_komponenter.png'); ?>" data-fancybox-group="roll_up_classic_carousel" title="Roll-Up Classic, Komponenter" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_komponenter.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" data-fancybox-group="roll_up_classic_carousel" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" data-fancybox-group="roll_up_classic_carousel" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//www.youtube.com/embed/40p-DopZBXI?rel=0&autoplay=1&controls=0" data-fancybox-group="roll_up_classic_carousel" class="various fancybox" data-fancybox-type="iframe">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large_video.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                </ul>
                                
                            </div>
                            
                            <div class="next">
                                <a href="#next"> <img src="/plugins/ldscarousel/img/next-arrow.png" /> </a>
                            </div>
                                
                            <div class="navigation">
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" class="focus"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                            </div>
                            
                        </div>

                        <div class="clear"></div>

                        <div class="content">
                            
                            <ul class="content_tabs four">
                                <li class="active">
                                    <a href="#beskrivning" title="Beskrivning"><img src="/img/ui/icons/information.svg" alt="Beskrivning"></a>
                                </li>
                                <li>
                                    <a href="#rabatter" title="Priser"><img src="/img/ui/icons/price.svg" alt="Priser"></a>
                                </li>
                                <li>
                                    <a href="#specifikation" title="Specifikationer"><img src="/img/ui/icons/list.svg" alt="Specifikationer"></a>
                                </li>
                                <li>
                                    <a href="#tillbehor" title="Tillbehör"><img src="/img/ui/icons/list.svg" alt="Tillbehör"></a>
                                </li>
                            </ul>
                            
                            <div class="content_information">
                                <div id="beskrivning" class="content_data active">
                                    <div class="columns_two">
                                    <h4>Beskrivning</h4>
                                    <?php
                                        $paragraphs = explode( "\r\n\r\n" , $value['product_description'] );
                                        foreach( $paragraphs  as $p_key => $p_value ){
                                            echo( "<p>".$p_value."</p>\n\n" );
                                        }
                                    ?>
                                    </div>
                                </div>

                                <div class="clear"></div>

                                <div id="rabatter" class="content_data">
                                <h4>Priser &amp; Mängdrabatter</h4>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>
                                                    Produkt / Antal
                                                </td>
                                                <td>
                                                    Pris
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <!-- @TODO Infoga Prisrabatterna för alla varianter här -->
                                        <?php
                                        $p_length = count( $value['prices'] );
                                        foreach( $value['prices'] as $p_key => $p_value ) { ?>
                                            <?php if( !isset( $price_variant ) ) {
                                                $price_variant = $p_value['product_name'];
                                            ?>
                                            <tr class="title">
                                                <td colspan="2">
                                                    <h5>
                                                        <?php echo( $price_variant ); ?>
                                                    </h5>
                                                </td>
                                            </tr>
                                            <?php
                                            } elseif( $p_value['product_name'] !== $price_variant ) {
                                                $price_variant = $p_value['product_name'];
                                            ?>
                                            <tr class="title">
                                                <td colspan="2">
                                                    <h5>
                                                        <?php echo( $price_variant ); ?>
                                                    </h5>
                                                </td>
                                            </tr>
                                            <?php
                                            } ?>
                                            <tr>
                                                <td>
                                                    <?php
                                                        if( is_null($p_value['min_amount']) && is_null($p_value['max_amount']) && $p_length >= 2 ) {
                                                            echo('1+');
                                                        } elseif( is_null($p_value['min_amount']) && is_null($p_value['max_amount']) ) {
                                                            echo('1');
                                                        } elseif( $p_value['min_amount'] === $p_value['max_amount'] ) {
                                                            echo($p_value['min_amount'].( $p_length >= 2 ? '+' : '' ) );
                                                        } else {
                                                            echo(
                                                                    $p_value['min_amount'].
                                                                    ( is_null($p_value['min_amount'] || $p_value['max_amount']) ? '' : ' - ').
                                                                    $p_value['max_amount']
                                                                );
                                                        }
                                                    ?>
                                                </td>
                                                <td>
                                                    <?php echo( $p_value['price'] ) ?>:-
                                                </td>
                                            </tr>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            
                            </div>
                        
                        </div>

                        <div class="clear"></div>
                        
                    </div>

                    <div class="clear"></div>
                    <?php } ?>