<?php

    $this->inlineScript()->appendFile( $this->basePath('/plugins/ldscarousel/js/jquery.ldscarousel.js') )
                         ->appendFile( $this->basePath('/js/products.js') );
    
    $this->headScript()->prependFile( $this->basePath('/plugins/validate/js/jquery.validate.js') )
                       ->prependFile( $this->basePath('/plugins/autogrow/js/jquery.input.autogrow.js') )
                       ->prependFile( $this->basePath('/plugins/fancybox/js/jquery.fancybox-thumbs.js') )
                       ->prependFile( $this->basePath('/plugins/fancybox/js/jquery.fancybox.js') );
    
    $this->headLink()->appendStylesheet( $this->basePath('/plugins/fancybox/css/jquery.fancybox.css') )
                     ->appendStylesheet( $this->basePath('/plugins/fancybox/css/jquery.fancybox-buttons.css') )
                     ->appendStylesheet( $this->basePath('/plugins/fancybox/css/jquery.fancybox-thumbs.css') )
                     ->appendStylesheet( $this->basePath('/plugins/ldscarousel/css/jquery.ldscarousel.css') )
                     ->appendStylesheet( $this->basePath('/css/products.css') );
?>
                    
                    <?php
                    foreach($this->resultset as $key => $value) {
                    $this->headTitle()->append( $value['product_name'] );
                    ?>
                    <h1><?php echo( $value['product_name'] ) ?></h1>
                    
                    <div class="clear"></div>
                            
                    <ul class='information'>
                        <li>
                            <a href="<?php echo $this->basePath('/tillverkare/'.$value['manufacturer_seo']) . PHP_EOL; ?>" title="<?php echo( $value['manufacturer'] ); ?>"><?php echo( $value['manufacturer'] ); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath('/kategori/roll_ups') . PHP_EOL; ?>" title="Roll-Ups">Roll-Ups</a>
                        </li>
                    </ul>
                    
                    <div class="splash container single backshadow product">

                        <div class="header drag_handle">
                            
                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount"><?php echo( $value['fran_price'] ); ?>:-</p>
                            </div>
                            
                            <div class="clear"></div>
                            
                            <form id="produkt-<?php echo( $value['product_id'] ); ?>-addtocart-form" class="buy">
                                
                                <div class="buy_element">
                                    <?php
                                        if( array_key_exists('variants', $value ) ) {
                                    ?>
                                    <label for="product-<?php echo( $value['product_id'] ); ?>-variants" class="antal"><?php echo( $value['variant_title'] ); ?></label>
                                    <select id="product-<?php echo( $value['product_id'] ); ?>-variants" title="Var god välj en <?php echo( $value['variant_title'] ); ?>" class="required" required>
                                        <option value=""></option>
                                        <?php foreach( $value['variants'] as $v_key => $v_value ) { ?>
                                        <option value="<?php echo( $v_value['product_id'] ); ?>" data-id="<?php echo( $v_value['product_id'] ); ?>" data-name="<?php echo( $v_value['product_name'] ); ?>" data-icon="rollup_classic_large.png" data-manufacturer="<?php echo( $v_value['manufacturer'] ); ?>" data-price="<?php echo( $v_value['fran_price'] ); ?>" data-vat="25">
                                            <?php echo( $v_value['product_variant'] ); ?> (från <?php echo( $v_value['fran_price'] ); ?>:-)
                                        </option>
                                        <?php } ?>
                                    </select>
                                    <?php } else { ?>
                                    <div id="product-<?php echo( $value['product_id'] ); ?>" class="hidden"></div>
                                    <?php } ?>
                                </div>
                                
                                <div class="add_to_cart buy_element">
                                    
                                    <div class="amount">
                                        <label for="produkt-<?php echo( $value['product_id'] ); ?>-antal" class="antal">Antal</label>
                                        <input id="produkt-<?php echo( $value['product_id'] ); ?>-antal" type="text" placeholder="0" minlength="1" class="antal required" required>
                                    </div>
                                    
                                    <button> Lägg i varukorgen </button>
                                    
                                </div>
                                
                                <div class="clear"></div>
                                
                            </form>
                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image carousel_wrapper">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            
                            <div class="prev">
                                <a href="#prev"> <img src="/plugins/ldscarousel/img/prev-arrow.png" /> </a>
                            </div>
                            
                            <div class="carousel">
                                
                                <ul>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" data-fancybox-group="roll_up_classic_carousel" title="Roll-Up Classic" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="focus">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_mekanik.png'); ?>" data-fancybox-group="roll_up_classic_carousel" title="Roll-Up Classic, Mekanik" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_mekanik.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_komponenter.png'); ?>" data-fancybox-group="roll_up_classic_carousel" title="Roll-Up Classic, Komponenter" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_komponenter.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" data-fancybox-group="roll_up_classic_carousel" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" data-fancybox-group="roll_up_classic_carousel" class="fancybox">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//www.youtube.com/embed/40p-DopZBXI?rel=0&autoplay=1&controls=0" data-fancybox-group="roll_up_classic_carousel" class="various fancybox" data-fancybox-type="iframe">
                                            <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large_video.png'); ?>" alt="Roll-Up Classic" class="">
                                        </a>
                                    </li>
                                </ul>
                                
                            </div>
                            
                            <div class="next">
                                <a href="#next"> <img src="/plugins/ldscarousel/img/next-arrow.png" /> </a>
                            </div>
                                
                            <div class="navigation">
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" class="focus"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                                <a href="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>"><span></span></a>
                            </div>
                            
                        </div>

                        <div class="clear"></div>

                        <div class="content">
                            
                            <ul class="content_tabs three">
                                <li class="active">
                                    <a href="#beskrivning" title="Beskrivning"><img src="/img/ui/icons/information.svg" alt="Beskrivning"></a>
                                </li>
                                <li>
                                    <a href="#rabatter" title="Priser"><img src="/img/ui/icons/price.svg" alt="Priser"></a>
                                </li>
                                <li>
                                    <a href="#tillbehor" title="Tillbehör"><img src="/img/ui/icons/additionals.svg" alt="Tillbehör"></a>
                                </li>
                            </ul>
                            
                            <div class="content_information">
                                <div id="beskrivning" class="content_data active">
                                    <div class="columns_two">
                                        <h4>Beskrivning</h4>
                                        <?php
                                            $paragraphs = explode( "\r\n\r\n" , $value['product_description'] );
                                            
                                            $this->headMeta()->appendName('description',$paragraphs[0]);
                                            
                                            foreach( $paragraphs  as $p_key => $p_value ){
                                                echo( "<p>".$p_value."</p>\n\n" );
                                            }
                                        ?>
                                    </div>
                                    <div>
                                        <h4>Specifikationer</h4>
                                    </div>
                                </div>

                                <div class="clear"></div>

                                <div id="rabatter" class="content_data">
                                <h4>Priser &amp; Mängdrabatter</h4>
                                    <table>
                                        <thead>
                                            <tr>
                                                <td>
                                                    Produkt / Antal
                                                </td>
                                                <td>
                                                    Pris
                                                </td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <!-- @TODO Infoga Prisrabatterna för alla varianter här -->
                                        <?php
                                        $p_length = count( $value['prices'] );
                                        foreach( $value['prices'] as $p_key => $p_value ) { ?>
                                            <?php if( !isset( $price_variant ) ) {
                                                $price_variant = $p_value['product_name'];
                                            ?>
                                            <tr class="title">
                                                <td colspan="2">
                                                    <h5>
                                                        <?php echo( $price_variant ); ?>
                                                    </h5>
                                                </td>
                                            </tr>
                                            <?php
                                            } elseif( $p_value['product_name'] !== $price_variant ) {
                                                $price_variant = $p_value['product_name'];
                                            ?>
                                            <tr class="title">
                                                <td colspan="2">
                                                    <h5>
                                                        <?php echo( $price_variant ); ?>
                                                    </h5>
                                                </td>
                                            </tr>
                                            <?php
                                            } ?>
                                            <tr>
                                                <td>
                                                    <?php
                                                        if( is_null($p_value['min_amount']) && is_null($p_value['max_amount']) && $p_length >= 2 ) {
                                                            echo('1+');
                                                        } elseif( is_null($p_value['min_amount']) && is_null($p_value['max_amount']) ) {
                                                            echo('1');
                                                        } elseif( $p_value['min_amount'] === $p_value['max_amount'] ) {
                                                            echo($p_value['min_amount'].( $p_length >= 2 ? '+' : '' ) );
                                                        } else {
                                                            echo(
                                                                    $p_value['min_amount'].
                                                                    ( is_null($p_value['min_amount'] || $p_value['max_amount']) ? '' : ' - ').
                                                                    $p_value['max_amount']
                                                                );
                                                        }
                                                    ?>
                                                </td>
                                                <td>
                                                    <?php echo( $p_value['price'] ) ?>:-
                                                </td>
                                            </tr>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            
                            </div>
                        
                        </div>

                        <div class="clear"></div>
                        
                    </div>

                    <div class="clear"></div>
                    <?php } ?>