
                    
                    <?php  foreach($this->resultset as $key => $value) { ?>
                    <h1><?php echo( $value['product_name'] ); ?></h1>
                    
                    <div class="splash container single backshadow product draggable">

                        <div class="header drag_handle">
                            
                            <div class="icon">
                                <img src="<?php echo $this->basePath('/img/manufacturers/logos/expolinc-logo.svg'); ?>" class="manufacturer icon">
                            </div>
                            
                            <div class="actions">
                                <ul>
                                    <li data-sidebar-interact='true' data-for='varukorg'>
                                        <a href="#buy" <?php if( array_key_exists('variants', $value ) ) { ?>class='has-children'<?php } ?>> <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> Köp </a>
                                        <div class="data hidden" data-id="<?php echo( $value['product_id'] ); ?>" data-name="<?php echo( $value['product_name'] ); ?>" data-icon="rollup_classic_large.png" data-manufacturer="<?php echo( $value['manufacturer'] ); ?>" data-price="<?php echo( $value['fran_price'] ); ?>" data-vat="25"></div>
                                        
                                        <?php if( array_key_exists('variants', $value ) ) { ?>
                                        <ul class="has-children backshadow">
                                            
                                            <?php foreach( $value['variants'] as $v_key => $v_value ) { ?>
                                            <li>
                                                <a href="#buy">
                                                    <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> <?php echo( $v_value['product_variant'] ); ?>
                                                    <div class="clear"></div>
                                                </a>
                                                <div class="data hidden" data-id="<?php echo( $v_value['product_id'] ); ?>" data-name="<?php echo( $v_value['product_name'] ); ?>" data-icon="rollup_classic_large.png" data-manufacturer="<?php echo( $v_value['manufacturer'] ); ?>" data-price="<?php echo( $v_value['fran_price'] ); ?>" data-vat="25"></div>
                                            </li>
                                            <?php } ?>
                                            
                                        </ul>
                                        <?php } ?>
                                        
                                    </li>
                                    <li> <a href="#add"> <img src="<?php echo $this->basePath('img/ui/icons/add_to_list.svg'); ?>"> Lägg till i lista </a> </li>
                                    <li>
                                        <input type="checkbox" id="compare-1" name="compare-1" class="compare">
                                        <label for="compare-1" class="compare">Jämför</label>
                                    </li>
                                </ul>
                            </div>

                            <h3><a href="<?php echo $this->basePath('/produkter/'.$value['product_seo']) . PHP_EOL; ?>" title="<?php echo( $value['product_name'] ); ?>"><?php echo( $value['product_name'] ); ?></a></h3>
                            
                            <ul class='information'>
                                <li>
                                    <a href="<?php echo $this->basePath('/tillverkare/'.$value['manufacturer_seo']) . PHP_EOL; ?>" title="<?php echo( $value['manufacturer'] ); ?>"><?php echo( $value['manufacturer'] ); ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('/kategori/roll_ups') . PHP_EOL; ?>" title="Roll-Ups">Roll-Ups</a>
                                </li>
                            </ul>
                            
                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount"><?php echo( $value['fran_price'] ); ?>:-</p>
                            </div>

                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            <div class="left"></div>
                            <div class="carousel">
                                
                                <ul>
                                    <li>
                                        <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="focus">
                                    </li>
                                    <li>
                                        <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                    </li>
                                    <li>
                                        <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                    </li>
                                    <li>
                                        <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                    </li>
                                    <li>
                                        <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="">
                                    </li>
                                </ul>
                                
                            </div>
                            <div class="right"></div>
                                
                            <div style="display:block;width:auto;margin: 0px auto;text-align:center;">
                                <a href="#" style="display:inline-block;box-sizing: border-box;height:10px;width:10px;background-color:#999;border-radius:5px;margin-right:5px;"></a>
                                <a href="#" style="display:inline-block;box-sizing: border-box;height:10px;width:10px;background-color:transparent;border: 2px solid #999;border-radius:5px;margin-right:5px;"></a>
                                <a href="#" style="display:inline-block;box-sizing: border-box;height:10px;width:10px;background-color:transparent;border: 2px solid #999;border-radius:5px;margin-right:5px;"></a>
                                <a href="#" style="display:inline-block;box-sizing: border-box;height:10px;width:10px;background-color:transparent;border: 2px solid #999;border-radius:5px;margin-right:5px;"></a>
                                <a href="#" style="display:inline-block;box-sizing: border-box;height:10px;width:10px;background-color:transparent;border: 2px solid #999;border-radius:5px;margin-right:5px;"></a>
                            </div>
                            
                        </div>

                        <div class="content">
                            <?php
                                $paragraphs = explode( "\r\n\r\n" , $value['product_description'] );
                                foreach( $paragraphs  as $p_key => $p_value ){
                                    echo( "<p>".$p_value."</p>\n\n" );
                                }
                            ?>
                        </div>
                        
                    </div>
                    <?php } ?>