<?php $ui_show = count( $media ) > 1 ? '' : 'hidden' ; ?>
                        <div class="image carousel_wrapper">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            
                            <div class="prev lds_carousel_ui <?php echo( $ui_show ) ?>">
                                <a href="#prev"> <img src="/plugins/ldscarousel/img/prev-arrow.png" /> </a>
                            </div>
                            
                            <div class="carousel">
                                
                                <ul>
                                <?php foreach($this->media as $media) : ?>
                                    
                                    <?php if($media['external_media'] == 'y') : ?>
                                        <?php if( $media['type_media'] == 'youtube' ) : ?>
                                        <li>
                                            <a href="http://www.youtube.com/embed/<?php echo($media['file_media']) ?>?rel=0&autoplay=1&controls=1" data-fancybox-group="product_image_carousel" title="<?php echo( $media['name_media'] ) ?>" class="various fancybox" data-fancybox-type="iframe">
                                                <img src="http://img.youtube.com/vi/<?php echo($media['file_media']) ?>/mqdefault.jpg" alt="<?php echo( $media['name_media'] ) ?>" class="youtube<?php if( $media['primary_media'] == 'y' ){ echo(' focus'); } ?>">
                                            </a>
                                        </li>
                                        <?php else : ?>
                                        <li>
                                            <a href="<?php echo($media['file_media']) ?>" data-fancybox-group="product_image_carousel" title="<?php echo( $media['name_media'] ) ?>" class="fancybox">
                                                <img src="<?php echo($media['file_media']) ?>" alt="<?php echo( $media['name_media'] ) ?>" class="<?php if( $media['primary_media'] == 'y' ){ echo('focus'); } ?>">
                                            </a>
                                        </li>
                                        <?php endif; ?>
                                    <?php else: ?>
                                    <li>
                                        <a href="<?php echo $this->basePath('media/upload/'.$media['file_media']); ?>" data-fancybox-group="product_image_carousel" title="<?php echo( $media['name_media'] ) ?>" class="fancybox">
                                            <img src="<?php echo $this->basePath('media/upload/'.$media['file_thumbnail']); ?>" alt="<?php echo( $media['name_media'] ) ?>" class="<?php if( $media['primary_media'] == 'y' ){ echo('focus'); } ?>">
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                </ul>
                                
                            </div>
                            
                            <div class="next lds_carousel_ui <?php echo( $ui_show ) ?>">
                                <a href="#next"> <img src="/plugins/ldscarousel/img/next-arrow.png" /> </a>
                            </div>
                                
                            <div class="navigation lds_carousel_ui <?php echo( $ui_show ) ?>">
                                <?php foreach($this->media as $media) : ?>
                                <a href="#" class="<?php if( $media['primary_media'] == 'y' ){ echo('focus'); } ?>"><span></span></a>
                                <?php endforeach; ?>
                            </div>
                            
                        </div>