

                    <h1><?php echo $this->translate('Utvalda Produkter'); ?></h1>
                    
                    <input type="radio" id="tab-4" name="listformat" class="list-type" data-format="boxes">
                    <label for="tab-4" class="list-type"></label>
                    
                    <input type="radio" id="tab-3" name="listformat" class="list-type" data-format="list">
                    <label for="tab-3" class="list-type"></label>
                    
                    <input type="radio" id="tab-2" name="listformat" class="list-type" data-format="compressed">
                    <label for="tab-2" class="list-type"></label>
                    
                    <input type="radio" id="tab-1" name="listformat" class="list-type" data-format="expanded" checked>
                    <label for="tab-1" class="list-type"></label>
                    
                    <div id="do_compare">
                        <a href="#compare">
                        <img src="<?php echo $this->basePath('img/ui/icons/magnifying_glass.svg') . PHP_EOL; ?>">
                            <div class="item_count">
                                <span>0</span>
                            </div>
                        </a>
                    </div>
                    
                    <div class="clear"></div>

                    <div class="splash container single backshadow">

                        <div class="header">
                            
                            <div class="icon">
                                <img src="<?php echo $this->basePath('img/manufacturers/logos/expolinc-logo.svg'); ?>" class="manufacturer icon">
                                <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" class="product icon">
                            </div>
                            
                            <div class="actions">
                                <ul>
                                    <li data-sidebar-interact='true' data-for='varukorg'>
                                        <a href="#buy"> <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> Köp </a>
                                        <div class="data hidden" data-id="1" data-name="Roll-Up Classic" data-icon="rollup_classic_large.png" data-manufacturer="Expolinc" data-price="2250" data-vat="25"></div>
                                        <ul class="has-children">
                                            <li>
                                                <a href="#buy">
                                                    <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> 85 x 215 cm
                                                    <div class="clear"></div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#buy">
                                                    <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> 100 x 215 cm
                                                    <div class="clear"></div>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#buy">
                                                    <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> 145 x 215 cm
                                                    <div class="clear"></div>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li> <a href="#add"> <img src="<?php echo $this->basePath('img/ui/icons/add_to_list.svg'); ?>"> Lägg till i lista </a> </li>
                                    <li>
                                        <input type="checkbox" id="compare-1" name="compare-1" class="compare">
                                        <label for="compare-1" class="compare">Jämför</label>
                                    </li>
                                </ul>
                            </div>

                            <h3><a href="<?php echo $this->basePath('/produkter/roll_up_classic') . PHP_EOL; ?>" title="Roll-Up Classic">Roll-Up Classic</a></h3>
                            <ul class='information'>
                                <li>
                                    <a href="<?php echo $this->basePath('/tillverkare/expolinc'). PHP_EOL; ?>" title="Expolinc">Expolinc</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('/kategori/roll_ups') . PHP_EOL; ?>" title="Roll-Ups">Roll-Ups</a>
                                </li>
                            </ul>

                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount">2250:-</p>
                            </div>

                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            <div class="carousel">
                                <img src="<?php echo $this->basePath('img/produkter/rollup_classic_large.png'); ?>" alt="Roll-Up Classic" class="focus">
                            </div>
                        </div>

                        <div class="content">
                            <p>
                                Roll Up Classic har av Föreningen Svensk Forms Opinionsnämnd fått utmärkelsen "brukskonst"!
                            </p>

                            <p>
                                Systemet är lätt att bära med sig och är snabbt klart för en presentation.
                            </p>

                            <p>
                                Roll Up Classic finns i flera olika bredder och är tänkt för upprepad användning i olika typer av miljöer.
                            </p>
                        </div>
                        
                    </div>

                    <div class="splash container single backshadow">

                        <div class="header">
                            
                            <div class="icon">
                                <img src="<?php echo $this->basePath('img/manufacturers/logos/expolinc-logo.svg'); ?>" class="manufacturer icon">
                                <img src="<?php echo $this->basePath('img/produkter/rollup_professional_large.png'); ?>" class="product icon">
                            </div>
                            
                            <div class="actions">
                                <ul>
                                    <li>
                                        <a href="#buy" data-sidebar-interact='true' data-for='varukorg'> <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> Köp </a>
                                        <div class="data hidden" data-id="2" data-name="Roll-Up Professional" data-icon="rollup_professional_large.png" data-manufacturer="Expolinc" data-price="2430" data-vat="25"></div>
                                    </li>
                                    <li> <a href="#add"> <img src="<?php echo $this->basePath('img/ui/icons/add_to_list.svg'); ?>"> Lägg till i lista </a> </li>
                                    <li>
                                        <input type="checkbox" id="compare-2" name="compare-2" class="compare">
                                        <label for="compare-2" class="compare">Jämför</label>
                                    </li>
                                </ul>
                            </div>

                            <h3><a href="<?php echo $this->basePath('/produkter/roll_up_professional') . PHP_EOL; ?>" title="Roll-Up Professional">Roll-Up Professional</a></h3>
                            <ul class='information'>
                                <li>
                                    <a href="<?php echo $this->basePath('/tillverkare/expolinc'). PHP_EOL; ?>" title="Expolinc">Expolinc</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('/kategori/roll_ups') . PHP_EOL; ?>" title="Roll-Ups">Roll-Ups</a>
                                </li>
                            </ul>

                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount">2430:-</p>
                            </div>

                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            <div class="carousel">
                                <img src="<?php echo $this->basePath('img/produkter/rollup_professional_large.png'); ?>" alt="Roll-Up Professional" class="focus">
                            </div>
                        </div>

                        <div class="content">
                            <p>
                                Roll Up Professional är ett lite exklusivare displaysystem gjort för användning vid upprepade tillfällen i alla tänkbara miljöer.
                            </p>
                            <p>
                                Roll Up Professional har ännu enklare bildbyten och finns även i ett dubbelsidigt utförande.
                            </p>
                            <p>
                                Ett självklart val för event- och promotionaktiviteter.
                            </p>
                        </div>
                        
                    </div>

                    <div class="splash container single backshadow">

                        <div class="header">
                            
                            <div class="icon">
                                <img src="<?php echo $this->basePath('img/manufacturers/logos/expolinc-logo.svg'); ?>" class="manufacturer icon">
                                <img src="<?php echo $this->basePath('img/produkter/rollup_compact_large.png'); ?>" class="product icon">
                            </div>
                            
                            <div class="actions">
                                <ul>
                                    <li>
                                        <a href="#buy" data-sidebar-interact='true' data-for='varukorg'> <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> Köp </a>
                                        <div class="data hidden" data-id="3" data-name="Roll-Up Compact" data-icon="rollup_compact_large.png" data-manufacturer="Expolinc" data-price="1730" data-vat="25"></div>
                                    </li>
                                    <li> <a href="#add"> <img src="<?php echo $this->basePath('img/ui/icons/add_to_list.svg'); ?>"> Lägg till i lista </a> </li>
                                    <li>
                                        <input type="checkbox" id="compare-3" name="compare-3" class="compare">
                                        <label for="compare-3" class="compare">Jämför</label>
                                    </li>
                                </ul>
                            </div>

                            <h3><a href="<?php echo $this->basePath('/produkter/roll_up_compact') . PHP_EOL; ?>" title="Roll-Up Compact">Roll-Up Compact</a></h3>
                            <ul class='information'>
                                <li>
                                    <a href="<?php echo $this->basePath('/tillverkare/expolinc'). PHP_EOL; ?>" title="Expolinc">Expolinc</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('/kategori/roll_ups') . PHP_EOL; ?>" title="Roll-Ups">Roll-Ups</a>
                                </li>
                            </ul>

                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount">1730:-</p>
                            </div>

                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            <div class="carousel">
                                <img src="<?php echo $this->basePath('img/produkter/rollup_compact_large.png'); ?>" alt="Roll-Up Compact" class="focus">
                            </div>
                        </div>

                        <div class="content">
                            <p>
                                Roll Up Compact är en kompakt och lätthanterlig Roll Up och de rundade hörnen och sidorna gör den behaglig att handskas med.
                            </p>
                            <p>
                                Den justerbara pinnen ger stor valfrihet vid val av bildmått och gör det lätt att sätta upp systemet utan att behöva sträcka sig.
                            </p>
                        </div>
                        
                    </div>

                    <div class="splash container single backshadow">

                        <div class="header">
                            
                            <div class="icon">
                                <img src="<?php echo $this->basePath('img/manufacturers/logos/expolinc-logo.svg'); ?>" class="manufacturer icon">
                                <img src="<?php echo $this->basePath('img/produkter/case_and_counter_large.png'); ?>" class="product icon">
                            </div>
                            
                            <div class="actions">
                                <ul>
                                    <li>
                                        <a href="#buy" data-sidebar-interact='true' data-for='varukorg'> <img src="<?php echo $this->basePath('img/ui/icons/buy.svg'); ?>"> Köp </a>
                                        <div class="data hidden" data-id="4" data-name="Case &amp; Counter" data-icon="case_and_counter_large.png" data-manufacturer="Expolinc" data-price="4490" data-vat="25"></div>
                                    </li>
                                    <li> <a href="#add"> <img src="<?php echo $this->basePath('img/ui/icons/add_to_list.svg'); ?>"> Lägg till i lista </a> </li>
                                    <li>
                                        <input type="checkbox" id="compare-4" name="compare-4" class="compare">
                                        <label for="compare-4" class="compare">Jämför</label>
                                    </li>
                                </ul>
                            </div>

                            <h3><a href="<?php echo $this->basePath('/produkter/case_and_counter') . PHP_EOL; ?>" title="Case &amp; Counter">Case &amp; Counter</a></h3>
                            <ul class='information'>
                                <li>
                                    <a href="<?php echo $this->basePath('/tillverkare/expolinc'). PHP_EOL; ?>" title="Expolinc">Expolinc</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath('/kategori/diskar_och_podium') . PHP_EOL; ?>" title="Roll-Ups">Diskar &amp; Podium</a>
                                </li>
                            </ul>

                            <div class="price">
                                <p class="fran">från</p>
                                <p class="amount">4990:-</p>
                            </div>

                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>

                        <div class="image">
                            <img src="<?php echo $this->basePath('img/ui/arrow_down_indicator.svg'); ?>" alt="Arrow Down Indicator" class="indicator">
                            <div class="carousel">
                                <img src="<?php echo $this->basePath('img/produkter/case_and_counter_large.png'); ?>" alt="Case &amp; Counter" class="focus">
                            </div>
                        </div>

                        <div class="content">
                            <p>
                                Expolinc Case &amp; Counter är en rymlig transportbox som på minuten konverteras till en snygg och stabil disk.
                            </p>
                            <p>
                                De mjuka, rundade hörnen på toppskivan skapar en inbjudande mötesplats samtidigt som du kan exponera ditt budskap på omslagspanelen.
                            </p>
                            <p>
                                Case & Counter finns som färdiga Pop Up-paket men kan med fördel även användas för transport av andra portabla displaysystem.
                            </p>
                        </div>
                        
                    </div>